// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ComandaX.Infrastructure;

#nullable disable

namespace ComandaX.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210000000_AddSubscriptionManagement")]
    partial class AddSubscriptionManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Schema for Subscription entity - snapshot based on current model
            modelBuilder.Entity("ComandaX.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbacatePayBillingId")
                        .HasColumnType("text");

                    b.Property<string>("AbacatePayCustomerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PriceInCentavos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscription");
                });

            // Foreign key relationship
            modelBuilder.Entity("ComandaX.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ComandaX.Domain.Entities.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("ComandaX.Domain.Entities.Subscription", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

#pragma warning restore 612, 618
        }
    }
}
